FROM amazon/aws-cli
COPY build.sh .
COPY BP-BASE-SHELL-STEPS .

ENV ACTIVITY_SUB_TASK_CODE BP-ECR-REPO-CREATION-TASK
ENV SLEEP_DURATION 5s
ENV AWS_REGION ""
ENV ECR_REPO_NAME ""
ENV AWS_ACCESS_KEY_ID ""
ENV AWS_SECRET_ACCESS_KEY ""
ENTRYPOINT [ "./build.sh" ]
