FROM amazon/aws-cli
COPY build.sh .
COPY BP-BASE-SHELL-STEPS .

ENV ACTIVITY_SUB_TASK_CODE BP-ECR-REPO-CREATION-TASK
ENV SLEEP_DURATION 5s
ENV AWS_REGION "us-east-2"
ENV ECR_REPO_NAME "dev7"
ENV AWS_ACCESS_KEY_ID ""
ENV AWS_SECRET_ACCESS_KEY ""
ENTRYPOINT [ "./build.sh" ]
